task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 3
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /mnt/e/Experiment/OpenDataLab___UAVDT/raw/UAV-benchmark-M
    ann_file: /mnt/e/Experiment/huya-deimv2/deimv2/uavdt_realtrain.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    # img_folder: /mnt/e/Experiment/OpenDataLab___UAVDT/raw/UAV-benchmark-M
    # ann_file: /mnt/e/Experiment/DEIMv2-main/uavdt_val.json
    img_folder: /mnt/e/Experiment/OpenDataLab___UAVDT/raw/UAV-benchmark-M
    ann_file: /mnt/e/Experiment/huya-deimv2/deimv2/uavdt_test.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction

test_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /mnt/e/Experiment/OpenDataLab___UAVDT/raw/UAV-benchmark-M
    ann_file: /mnt/e/Experiment/huya-deimv2/deimv2/uavdt_test.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction